apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nosql-api-monitor
  namespace: observability
  labels:
    app: api
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
    - nosql-showdown
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s