apiVersion: v1
kind: Service
metadata:
  name: grafana-lb
  namespace: observability
  labels:
    app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.245
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: kube-prom-stack