apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-extra-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
    # Scrape API metrics
    - job_name: 'nosql-api'
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - nosql-showdown
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        action: keep
        regex: api
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - target_label: __address__
        replacement: '#{__meta_kubernetes_pod_ip}:9091'
    
    # Scrape MongoDB metrics
    - job_name: 'mongodb'
      static_configs:
      - targets: ['mongodb.databases.svc.cluster.local:27017']
    
    # Scrape Elasticsearch metrics
    - job_name: 'elasticsearch'
      static_configs:
      - targets: ['elasticsearch.databases.svc.cluster.local:9200']
      metrics_path: '/_prometheus/metrics'