apiVersion: v1
kind: Service
metadata:
  name: api-metrics
  namespace: nosql-showdown
  labels:
    app: api
    component: backend
spec:
  selector:
    app: api
  ports:
  - name: metrics
    port: 9091
    targetPort: 9091
    protocol: TCP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: api-monitor
  namespace: nosql-showdown
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s