apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nosql-showdown
type: Opaque
stringData:
  POSTGRES_USER: showdown_user
  POSTGRES_PASSWORD: showdown_pass_2024
  POSTGRES_DB: showdown_db 