apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: nosql-showdown
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: prisma-migrate
        image: nosql-showdown-api:latest
        imagePullPolicy: Never
        command: ["npx", "prisma", "migrate", "deploy"]
        env:
        - name: DATABASE_URL
          value: "postgresql://showdown_user:showdown_pass_2024@postgres.nosql-showdown.svc.cluster.local:5432/showdown_db" 