apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-nginx-config
  namespace: nosql-showdown
data:
  default.conf: |
    server {
        listen 80;
        server_name _;
        
        root /usr/share/nginx/html;
        index index.html;
        
        # Proxy API requests to the backend service
        location /api/ {
            proxy_pass http://api.nosql-showdown.svc.cluster.local:3000/api/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Proxy Socket.io
        location /socket.io/ {
            proxy_pass http://api.nosql-showdown.svc.cluster.local:3000/socket.io/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_read_timeout 120s;
            proxy_send_timeout 120s;
        }
        
        # Health check endpoint
        location /health {
            return 200 "OK";
            add_header Content-Type text/plain;
        }
        
        # Serve static files
        location / {
            try_files $uri $uri/ /index.html;
        }
    }