apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: nosql-showdown
  labels:
    app: api
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        component: backend
    spec:
      containers:
      - name: api
        image: nosql-showdown-api:v1.1.0
        imagePullPolicy: Never  # For local development
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9091
          name: metrics
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          value: "postgresql://showdown_user:showdown_pass_2024@postgres.nosql-showdown.svc.cluster.local:5432/showdown_db"
        - name: MONGODB_URL
          value: "mongodb://admin:mongodb_pass_2024@mongodb.databases.svc.cluster.local:27017/showdown_benchmark?authSource=admin"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch.databases.svc.cluster.local:9200"
        - name: CORS_ORIGIN
          value: "http://localhost:3000,http://localhost:3001,http://localhost:3002,http://localhost:3003"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5 