apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: nosql-showdown
  labels:
    app: ui
    component: frontend
    platform: arm64
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
        component: frontend
    spec:
      initContainers:
      # Fix hardcoded URLs before starting nginx
      - name: fix-urls
        image: reinoutw/nosql-showdown-ui:pi-1.0.0
        command: ["/bin/sh"]
        args: 
        - -c
        - |
          echo "Fixing hardcoded API URLs..."
          cd /usr/share/nginx/html
          find . -name "*.js" -type f -exec sed -i 's|http://localhost:3000/api|/api|g' {} + || true
          find . -name "*.js" -type f -exec sed -i 's|http://localhost:3000|'|g' {} + || true
          find . -name "*.js" -type f -exec sed -i 's|ws://localhost:3000|'|g' {} + || true
          find . -name "*.js" -type f -exec sed -i 's|localhost:3000|'|g' {} + || true
          echo "URLs fixed!"
          cp -r /usr/share/nginx/html/* /fixed-html/
        volumeMounts:
        - name: fixed-html
          mountPath: /fixed-html
      containers:
      - name: ui
        image: reinoutw/nosql-showdown-ui:pi-1.0.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        - name: fixed-html
          mountPath: /usr/share/nginx/html
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      volumes:
      - name: nginx-config
        configMap:
          name: ui-nginx-config
      - name: fixed-html
        emptyDir: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: nosql-showdown
  labels:
    app: ui
    component: frontend
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.1.243
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ui