apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: nosql-showdown
  labels:
    app: api
    component: backend
spec:
  type: LoadBalancer
  selector:
    app: api
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    protocol: TCP
  - name: metrics
    port: 9091
    targetPort: 9091
    protocol: TCP 